spring:
  datasource:
    # Prioritize Neon/External URL from .env, fallback to internal docker network DB
    url: ${CUSTOM_DEV_DB_URL:jdbc:postgresql://localhost:5433/meetstudent}
    username: ${POSTGRES_USER:ibrahima}
    password: ${POSTGRES_PASSWORD:changeMeInProd!}
  
  jpa:
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:dockerSecretKeyForInternalOnly!1234567890}
