--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.roles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    description character varying(255)
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    birthday timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) UNIQUE,
    firstname character varying(100),
    lastname character varying(50),
    modified_at timestamp(6) without time zone NOT NULL,
    password character varying(255),
    role_id integer REFERENCES public.roles(id),
    speciality character varying(100)
);


--
-- Name: schools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.schools (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    city character varying(255),
    country character varying(255),
    location character varying(255),
    creation timestamp(6) without time zone
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.courses (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50)
);


--
-- Name: programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.programs (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    duration integer,
    school_id integer REFERENCES public.schools(id)
);


--
-- Name: accreditations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.accreditations (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50)
);


--
-- Name: program_accreditations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.program_accreditations (
    ends integer,
    starts integer,
    accreditation_id integer NOT NULL REFERENCES public.accreditations(id),
    program_id integer NOT NULL REFERENCES public.programs(id),
    PRIMARY KEY (accreditation_id, program_id)
);


--
-- Name: diploma; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.diploma (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    year_of timestamp(6) without time zone
);


--
-- Name: diploma_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.diploma_users (
    diploma_id integer NOT NULL REFERENCES public.diploma(id),
    user_id integer NOT NULL REFERENCES public.users(id),
    PRIMARY KEY (diploma_id, user_id)
);


--
-- Name: rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.rates (
    rated_entity character varying(31) NOT NULL,
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    comment character varying(150),
    note double precision,
    user_id integer REFERENCES public.users(id),
    course_id integer REFERENCES public.courses(id),
    program_id integer REFERENCES public.programs(id),
    school_id integer REFERENCES public.schools(id)
);