--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (1b53132)
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- Name: neon_auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA neon_auth;


--
-- Name: session(); Type: FUNCTION; Schema: auth; Owner: -
--

CREATE FUNCTION auth.session() RETURNS jsonb
    LANGUAGE sql STABLE
    AS $$
SELECT NULLIF(current_setting('request.jwt.claims', true), '')::jsonb
$$;


--
-- Name: user_id(); Type: FUNCTION; Schema: auth; Owner: -
--

CREATE FUNCTION auth.user_id() RETURNS text
    LANGUAGE sql STABLE
    AS $$
SELECT auth.session()->>'sub'
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users_sync; Type: TABLE; Schema: neon_auth; Owner: -
--

CREATE TABLE neon_auth.users_sync (
    raw_json jsonb NOT NULL,
    id text GENERATED ALWAYS AS ((raw_json ->> 'id'::text)) STORED NOT NULL,
    name text GENERATED ALWAYS AS ((raw_json ->> 'display_name'::text)) STORED,
    email text GENERATED ALWAYS AS ((raw_json ->> 'primary_email'::text)) STORED,
    created_at timestamp with time zone GENERATED ALWAYS AS (to_timestamp((trunc((((raw_json ->> 'signed_up_at_millis'::text))::bigint)::double precision) / (1000)::double precision))) STORED,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);


--
-- Name: accreditations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accreditations (
    id integer NOT NULL,
    code character varying(5),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50)
);


--
-- Name: accreditations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accreditations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accreditations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    code character varying(5),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50)
);


--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diploma; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diploma (
    id integer NOT NULL,
    name character varying(255),
    year_of timestamp(6) without time zone
);


--
-- Name: diploma_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diploma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diploma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diploma_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diploma_users (
    diploma_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: program_accreditations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program_accreditations (
    ends integer,
    starts integer,
    accreditation_id integer NOT NULL,
    program_id integer NOT NULL
);


--
-- Name: programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs (
    id integer NOT NULL,
    code character varying(5),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    duration integer,
    school_id integer
);


--
-- Name: programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rates (
    rated_entity character varying(31) NOT NULL,
    id integer NOT NULL,
    code character varying(5),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    comment character varying(150),
    note double precision,
    user_id integer,
    course_id integer,
    program_id integer,
    school_id integer
);


--
-- Name: rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schools (
    id integer NOT NULL,
    code character varying(5),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    city character varying(255),
    country character varying(255),
    location character varying(255),
    creation timestamp(6) without time zone
);


--
-- Name: schools_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    birthday timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    firstname character varying(100),
    lastname character varying(50),
    modified_at timestamp(6) without time zone NOT NULL,
    password character varying(255),
    role character varying(255),
    speciality character varying(100),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'EXPERT'::character varying, 'STUDENT'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_sync users_sync_pkey; Type: CONSTRAINT; Schema: neon_auth; Owner: -
--

ALTER TABLE ONLY neon_auth.users_sync
    ADD CONSTRAINT users_sync_pkey PRIMARY KEY (id);


--
-- Name: accreditations accreditations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accreditations
    ADD CONSTRAINT accreditations_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: diploma diploma_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diploma
    ADD CONSTRAINT diploma_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: program_accreditations program_accreditations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_accreditations
    ADD CONSTRAINT program_accreditations_pkey PRIMARY KEY (accreditation_id, program_id);


--
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (id);


--
-- Name: rates rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT rates_pkey PRIMARY KEY (id);


--
-- Name: schools schools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools
    ADD CONSTRAINT schools_pkey PRIMARY KEY (id);


--
-- Name: courses uk61og8rbqdd2y28rx2et5fdnxd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT uk61og8rbqdd2y28rx2et5fdnxd UNIQUE (code);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: accreditations ukdruss606vs79pw6voi8ovw0po; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accreditations
    ADD CONSTRAINT ukdruss606vs79pw6voi8ovw0po UNIQUE (code);


--
-- Name: schools ukm5x8j64nhdcprk9ghc6622swx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schools
    ADD CONSTRAINT ukm5x8j64nhdcprk9ghc6622swx UNIQUE (code);


--
-- Name: programs ukpry5cowyujos5wcl2tjfu9hpb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT ukpry5cowyujos5wcl2tjfu9hpb UNIQUE (code);


--
-- Name: rates ukrj4h74312htx9husuv0wec5gt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT ukrj4h74312htx9husuv0wec5gt UNIQUE (code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_sync_deleted_at_idx; Type: INDEX; Schema: neon_auth; Owner: -
--

CREATE INDEX users_sync_deleted_at_idx ON neon_auth.users_sync USING btree (deleted_at);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: diploma_users fk3oismpybgd2ydxpriakk259qo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diploma_users
    ADD CONSTRAINT fk3oismpybgd2ydxpriakk259qo FOREIGN KEY (diploma_id) REFERENCES public.diploma(id);


--
-- Name: diploma_users fk42l6x4a7h5d3vyiacp9kilyem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diploma_users
    ADD CONSTRAINT fk42l6x4a7h5d3vyiacp9kilyem FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: programs fk788wl7mf99opq8oqiu24rs9ai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT fk788wl7mf99opq8oqiu24rs9ai FOREIGN KEY (school_id) REFERENCES public.schools(id);


--
-- Name: rates fkabii5brbjlw7c1tst44r8fgb7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT fkabii5brbjlw7c1tst44r8fgb7 FOREIGN KEY (school_id) REFERENCES public.schools(id);


--
-- Name: rates fkanlgavwqngljux10mtly8qr6f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT fkanlgavwqngljux10mtly8qr6f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: program_accreditations fkduj7tgc3qolx3gl0e58kng3gk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_accreditations
    ADD CONSTRAINT fkduj7tgc3qolx3gl0e58kng3gk FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: rates fkhurhbvo0rk0xny5abjc2m2gbw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT fkhurhbvo0rk0xny5abjc2m2gbw FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: rates fkt5wuc6askynohbdaqeaj5wjeq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rates
    ADD CONSTRAINT fkt5wuc6askynohbdaqeaj5wjeq FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: program_accreditations fkta2fyyepp896b9kobbm3r9l68; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_accreditations
    ADD CONSTRAINT fkta2fyyepp896b9kobbm3r9l68 FOREIGN KEY (accreditation_id) REFERENCES public.accreditations(id);


--
-- Name: SCHEMA auth; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA auth TO authenticated;
GRANT USAGE ON SCHEMA auth TO anonymous;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO anonymous;


--
-- Name: TABLE accreditations; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.accreditations TO authenticated;
GRANT SELECT ON TABLE public.accreditations TO anonymous;


--
-- Name: SEQUENCE accreditations_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.accreditations_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.accreditations_id_seq TO anonymous;


--
-- Name: TABLE courses; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.courses TO authenticated;
GRANT SELECT ON TABLE public.courses TO anonymous;


--
-- Name: SEQUENCE courses_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.courses_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.courses_id_seq TO anonymous;


--
-- Name: TABLE diploma; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.diploma TO authenticated;
GRANT SELECT ON TABLE public.diploma TO anonymous;


--
-- Name: SEQUENCE diploma_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.diploma_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.diploma_id_seq TO anonymous;


--
-- Name: TABLE diploma_users; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.diploma_users TO authenticated;
GRANT SELECT ON TABLE public.diploma_users TO anonymous;


--
-- Name: TABLE flyway_schema_history; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.flyway_schema_history TO authenticated;
GRANT SELECT ON TABLE public.flyway_schema_history TO anonymous;


--
-- Name: TABLE program_accreditations; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.program_accreditations TO authenticated;
GRANT SELECT ON TABLE public.program_accreditations TO anonymous;


--
-- Name: TABLE programs; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.programs TO authenticated;
GRANT SELECT ON TABLE public.programs TO anonymous;


--
-- Name: SEQUENCE programs_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.programs_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.programs_id_seq TO anonymous;


--
-- Name: TABLE rates; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.rates TO authenticated;
GRANT SELECT ON TABLE public.rates TO anonymous;


--
-- Name: SEQUENCE rates_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.rates_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.rates_id_seq TO anonymous;


--
-- Name: TABLE schools; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.schools TO authenticated;
GRANT SELECT ON TABLE public.schools TO anonymous;


--
-- Name: SEQUENCE schools_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.schools_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.schools_id_seq TO anonymous;


--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.users TO authenticated;
GRANT SELECT ON TABLE public.users TO anonymous;


--
-- Name: SEQUENCE users_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT USAGE ON SEQUENCE public.users_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.users_id_seq TO anonymous;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT USAGE ON SEQUENCES TO anonymous;
ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT USAGE ON SEQUENCES TO authenticated;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT ALL ON FUNCTIONS TO anonymous;
ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT SELECT ON TABLES TO anonymous;
ALTER DEFAULT PRIVILEGES FOR ROLE meetstudent_owner IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO authenticated;


--
-- PostgreSQL database dump complete
--

