-- Create school_rates
CREATE TABLE school_rates (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    comment character varying(150),
    note double precision,
    user_id integer REFERENCES users(id),
    school_id integer REFERENCES schools(id)
);

-- Create program_rates
CREATE TABLE program_rates (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    comment character varying(150),
    note double precision,
    user_id integer REFERENCES users(id),
    program_id integer REFERENCES programs(id)
);

-- Create course_rates
CREATE TABLE course_rates (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer,
    name character varying(50),
    comment character varying(150),
    note double precision,
    user_id integer REFERENCES users(id),
    course_id integer REFERENCES courses(id)
);

-- Migrate data
INSERT INTO school_rates (id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, school_id)
SELECT id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, school_id
FROM rates
WHERE rated_entity = 'SCHOOL';

INSERT INTO program_rates (id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, program_id)
SELECT id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, program_id
FROM rates
WHERE rated_entity = 'PROGRAM';

INSERT INTO course_rates (id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, course_id)
SELECT id, code, created_at, created_by, modified_at, modified_by, name, comment, note, user_id, course_id
FROM rates
WHERE rated_entity = 'COURSE';

-- Drop old table
DROP TABLE rates;
