spring:
#    profiles:
#        active: dev,test,prod
    application:
        name: meetstudent
    datasource:
        password: changeMeInProd!
        username: ibrahima
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5435/meetstudent
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration