server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-path: always

spring:
#    profiles:
#        active: dev,test,prod
    application:
        name: meetstudent
    datasource:
        password: changeMeInProd!
        username: ibrahima
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5435/meetstudent
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: never
    flyway:
        enabled: true
        locations: classpath:db/migration