ALTER TABLE programs
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS modified_at TIMESTAMP;

ALTER TABLE courses
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS modified_at TIMESTAMP;