server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-path: always

spring:
    profiles:
        active: dev # You can specify multiple active profiles as a comma-separated list (e.g. dev,test,prod)
    application:
        name: meetstudent
    datasource:
        password: ${PGPASSWORD}
        username: ${PGUSER}
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${PGHOST}/${PGDATABASE}?sslmode=require
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: never
    flyway:
        enabled: true
        locations: classpath:db/migration
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true