CREATE TABLE tags (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL UNIQUE,
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer
);

CREATE TABLE school_tags (
    school_id integer NOT NULL REFERENCES schools(id),
    tag_id integer NOT NULL REFERENCES tags(id),
    PRIMARY KEY (school_id, tag_id)
);
