CREATE TABLE IF NOT EXISTS refresh_tokens (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token varchar(255) NOT NULL UNIQUE,
    expiry_date timestamp with time zone NOT NULL,
    user_id integer REFERENCES users(id),
    created_at timestamp(6) without time zone,
    created_by integer,
    modified_at timestamp(6) without time zone,
    modified_by integer
);
