CREATE TABLE IF NOT EXISTS media (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    storage_key varchar(512) NOT NULL,
    original_filename varchar(255),
    content_type varchar(128),
    size_bytes bigint,
    category varchar(32) NOT NULL,
    visibility varchar(16) NOT NULL,
    owner_id integer REFERENCES users(id),
    verification_status varchar(16),
    rejection_reason varchar(500),
    idempotency_key varchar(128),
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    created_by integer,
    modified_by integer,
    CONSTRAINT uq_media_owner_idempotency UNIQUE (owner_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_media_owner ON media (owner_id);
CREATE INDEX IF NOT EXISTS idx_media_status ON media (verification_status);
